"""minor fix user profile table

Revision ID: 078e6b59ccc3
Revises: fd73161e0646
Create Date: 2023-01-23 00:00:39.198302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '078e6b59ccc3'
down_revision = 'fd73161e0646'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
