"""added soft and technical skills table

Revision ID: 0e760b00f306
Revises: 078e6b59ccc3
Create Date: 2023-01-23 00:09:57.539620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e760b00f306'
down_revision = '078e6b59ccc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profileId', sa.Integer(), nullable=False),
    sa.Column('currentJobTitle', sa.String(), nullable=True),
    sa.Column('totalExperience', sa.String(), nullable=True),
    sa.Column('currentCompany', sa.String(), nullable=True),
    sa.Column('currentIndustry', sa.String(), nullable=True),
    sa.Column('noticePeriod', sa.String(), nullable=True),
    sa.Column('negotiableNoticePeriod', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('publicCompetitionLink', sa.String(), nullable=True),
    sa.Column('publicCompetitionScores', sa.String(), nullable=True),
    sa.Column('websiteUrl', sa.String(), nullable=True),
    sa.Column('linkedInUrl', sa.String(), nullable=True),
    sa.Column('githubUrl', sa.String(), nullable=True),
    sa.Column('twitterUrl', sa.String(), nullable=True),
    sa.Column('mediumUrl', sa.String(), nullable=True),
    sa.Column('behanceUrl', sa.String(), nullable=True),
    sa.Column('otherUrl', sa.String(), nullable=True),
    sa.Column('fixedPay', sa.String(), nullable=True),
    sa.Column('incentives', sa.String(), nullable=True),
    sa.Column('bonus', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('expectedCtc', sa.String(), nullable=True),
    sa.Column('negotiableExpectedCtc', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('bechelorsDegree', sa.String(), nullable=True),
    sa.Column('mastersDegree', sa.String(), nullable=True),
    sa.Column('phd', sa.String(), nullable=True),
    sa.Column('deplomaCourse', sa.String(), nullable=True),
    sa.Column('lastLogin', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profileId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technical_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userProfileId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('experience', sa.String(), nullable=True),
    sa.Column('experienceLevel', sa.String(), nullable=True),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userProfileId'], ['users_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'soft_skills', 'users_profile', ['userProfileId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'soft_skills', type_='foreignkey')
    op.drop_table('technical_skills')
    op.drop_table('users_profile')
    # ### end Alembic commands ###
