"""updated application table

Revision ID: 4e68acdc9dd0
Revises: bd3833d04877
Create Date: 2023-03-06 13:28:41.638875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e68acdc9dd0'
down_revision = 'bd3833d04877'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('applications', sa.Column('recruiterId', sa.Integer(), nullable=False))
    op.add_column('applications', sa.Column('createdAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('applications', sa.Column('updatedAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(None, 'applications', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'applications', 'recruiter_profile', ['recruiterId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_column('applications', 'updatedAt')
    op.drop_column('applications', 'createdAt')
    op.drop_column('applications', 'recruiterId')
    op.drop_column('applications', 'owner_id')
    # ### end Alembic commands ###
