"""updated posts model table

Revision ID: 867ca90eacbb
Revises: de958bc8a12d
Create Date: 2023-01-21 14:39:30.924693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '867ca90eacbb'
down_revision = 'de958bc8a12d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('salaryRange', sa.String(), nullable=False),
    sa.Column('communicationLang', sa.String(), nullable=True),
    sa.Column('joiningPeriod', sa.String(), nullable=True),
    sa.Column('workLocation', sa.String(), nullable=True),
    sa.Column('officeLocation', sa.String(), nullable=True),
    sa.Column('jobType', sa.String(), nullable=True),
    sa.Column('jobLevel', sa.String(), nullable=True),
    sa.Column('jobStage', sa.String(), nullable=True),
    sa.Column('jobDomain', sa.String(), nullable=True),
    sa.Column('educationLevel', sa.String(), nullable=True),
    sa.Column('experienceLevel', sa.String(), nullable=True),
    sa.Column('numberOfPositionOpen', sa.String(), nullable=True),
    sa.Column('rolesAndResponsibilities', sa.String(), nullable=True),
    sa.Column('reportingTo', sa.String(), nullable=True),
    sa.Column('screeningRounds', sa.String(), nullable=True),
    sa.Column('backgroundVerificationApplicable', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('benifitsProvided', sa.String(), nullable=True),
    sa.Column('published', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('postTimePeriod', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('recruiterId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recruiterId'], ['recruiter_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'reviews', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_table('posts')
    # ### end Alembic commands ###
