"""added experience table

Revision ID: a5d2bf5b7ac4
Revises: faa79dff7198
Create Date: 2023-01-23 17:36:13.049428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5d2bf5b7ac4'
down_revision = 'faa79dff7198'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userProfileId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('jobType', sa.String(), nullable=True),
    sa.Column('jobLocation', sa.String(), nullable=True),
    sa.Column('jobDomain', sa.String(), nullable=True),
    sa.Column('skills', sa.String(), nullable=True),
    sa.Column('startDate', sa.TIMESTAMP(), nullable=True),
    sa.Column('endDate', sa.TIMESTAMP(), nullable=True),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userProfileId'], ['users_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experience')
    # ### end Alembic commands ###
