"""all models table

Revision ID: c8d041ddb277
Revises: 
Create Date: 2023-01-26 18:29:33.064794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8d041ddb277'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('firstName', sa.String(), nullable=True),
    sa.Column('lastName', sa.String(), nullable=True),
    sa.Column('dateOfBirth', sa.String(), nullable=True),
    sa.Column('age', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('profilePicUrl', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('phoneVerified', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('emailVerified', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('isVerified', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('isBlocked', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('otpCode', sa.String(), nullable=True),
    sa.Column('deviceType', sa.String(), nullable=True),
    sa.Column('lastLogin', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workEmail', sa.String(), nullable=True),
    sa.Column('profileType', sa.Integer(), nullable=True),
    sa.Column('requisitionId', sa.Integer(), nullable=True),
    sa.Column('profileId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('recruiter_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jobTitle', sa.String(), nullable=True),
    sa.Column('companyName', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('noticePeriod', sa.String(), nullable=True),
    sa.Column('websiteUrl', sa.String(), nullable=True),
    sa.Column('linkedInUrl', sa.String(), nullable=True),
    sa.Column('otherUrl', sa.String(), nullable=True),
    sa.Column('profilePicUrl', sa.String(), nullable=True),
    sa.Column('bannerPicUrl', sa.String(), nullable=True),
    sa.Column('hiringRoleTitle', sa.String(), nullable=True),
    sa.Column('hiringRoleDescription', sa.String(), nullable=True),
    sa.Column('lastLogin', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('isCompanyAdmin', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profileId', sa.Integer(), nullable=False),
    sa.Column('currentJobTitle', sa.String(), nullable=True),
    sa.Column('totalExperience', sa.String(), nullable=True),
    sa.Column('currentCompany', sa.String(), nullable=True),
    sa.Column('currentIndustry', sa.String(), nullable=True),
    sa.Column('noticePeriod', sa.String(), nullable=True),
    sa.Column('negotiableNoticePeriod', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('publicCompetitionLink', sa.String(), nullable=True),
    sa.Column('publicCompetitionScores', sa.String(), nullable=True),
    sa.Column('websiteUrl', sa.String(), nullable=True),
    sa.Column('linkedInUrl', sa.String(), nullable=True),
    sa.Column('githubUrl', sa.String(), nullable=True),
    sa.Column('twitterUrl', sa.String(), nullable=True),
    sa.Column('mediumUrl', sa.String(), nullable=True),
    sa.Column('behanceUrl', sa.String(), nullable=True),
    sa.Column('otherUrl', sa.String(), nullable=True),
    sa.Column('fixedPay', sa.String(), nullable=True),
    sa.Column('incentives', sa.String(), nullable=True),
    sa.Column('bonus', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('expectedCtc', sa.String(), nullable=True),
    sa.Column('negotiableExpectedCtc', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('bechelorsDegree', sa.String(), nullable=True),
    sa.Column('mastersDegree', sa.String(), nullable=True),
    sa.Column('phd', sa.String(), nullable=True),
    sa.Column('deplomaCourse', sa.String(), nullable=True),
    sa.Column('lastLogin', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profileId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userProfileId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('licenceNumber', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('skills', sa.String(), nullable=True),
    sa.Column('startDate', sa.TIMESTAMP(), nullable=True),
    sa.Column('endDate', sa.TIMESTAMP(), nullable=True),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userProfileId'], ['users_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recruiterId', sa.Integer(), nullable=True),
    sa.Column('adminId', sa.Integer(), nullable=True),
    sa.Column('companyName', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('totalEmployees', sa.Integer(), nullable=True),
    sa.Column('headquartered', sa.String(), nullable=True),
    sa.Column('companyBio', sa.String(), nullable=True),
    sa.Column('companyEmail', sa.String(), nullable=True),
    sa.Column('profilePicUrl', sa.String(), nullable=True),
    sa.Column('bannerPicUrl', sa.String(), nullable=True),
    sa.Column('companyPics', sa.String(), nullable=True),
    sa.Column('founders', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('companyGst', sa.String(), nullable=True),
    sa.Column('websiteLink', sa.String(), nullable=True),
    sa.Column('phoneVerified', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('isVerified', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('isBlocked', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('lastLogin', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['adminId'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recruiterId'], ['recruiter_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userProfileId', sa.Integer(), nullable=False),
    sa.Column('course', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('school', sa.String(), nullable=True),
    sa.Column('startDate', sa.TIMESTAMP(), nullable=True),
    sa.Column('endDate', sa.TIMESTAMP(), nullable=True),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userProfileId'], ['users_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userProfileId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('jobType', sa.String(), nullable=True),
    sa.Column('jobLocation', sa.String(), nullable=True),
    sa.Column('jobDomain', sa.String(), nullable=True),
    sa.Column('skills', sa.String(), nullable=True),
    sa.Column('startDate', sa.TIMESTAMP(), nullable=True),
    sa.Column('endDate', sa.TIMESTAMP(), nullable=True),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userProfileId'], ['users_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('salaryRange', sa.String(), nullable=False),
    sa.Column('communicationLang', sa.String(), nullable=True),
    sa.Column('joiningPeriod', sa.String(), nullable=True),
    sa.Column('workLocation', sa.String(), nullable=True),
    sa.Column('officeLocation', sa.String(), nullable=True),
    sa.Column('jobType', sa.String(), nullable=True),
    sa.Column('jobLevel', sa.String(), nullable=True),
    sa.Column('jobStage', sa.String(), nullable=True),
    sa.Column('jobDomain', sa.String(), nullable=True),
    sa.Column('educationLevel', sa.String(), nullable=True),
    sa.Column('experienceLevel', sa.String(), nullable=True),
    sa.Column('numberOfPositionOpen', sa.String(), nullable=True),
    sa.Column('rolesAndResponsibilities', sa.String(), nullable=True),
    sa.Column('reportingTo', sa.String(), nullable=True),
    sa.Column('screeningRounds', sa.String(), nullable=True),
    sa.Column('backgroundVerificationApplicable', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('benifitsProvided', sa.String(), nullable=True),
    sa.Column('published', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('postTimePeriod', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('recruiterId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recruiterId'], ['recruiter_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userProfileId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('skills', sa.String(), nullable=True),
    sa.Column('startDate', sa.TIMESTAMP(), nullable=True),
    sa.Column('endDate', sa.TIMESTAMP(), nullable=True),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userProfileId'], ['users_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('soft_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userProfileId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('experience', sa.String(), nullable=True),
    sa.Column('experienceLevel', sa.String(), nullable=True),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userProfileId'], ['users_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technical_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userProfileId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('experience', sa.String(), nullable=True),
    sa.Column('experienceLevel', sa.String(), nullable=True),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userProfileId'], ['users_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('ratings', sa.Integer(), nullable=True),
    sa.Column('reviews', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('technical_skills')
    op.drop_table('soft_skills')
    op.drop_table('projects')
    op.drop_table('posts')
    op.drop_table('experience')
    op.drop_table('education')
    op.drop_table('companies')
    op.drop_table('certificates')
    op.drop_table('users_profile')
    op.drop_table('recruiter_profile')
    op.drop_table('users')
    # ### end Alembic commands ###
