"""added certificates projects table

Revision ID: db6dc079014c
Revises: a5d2bf5b7ac4
Create Date: 2023-01-23 18:13:03.367138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db6dc079014c'
down_revision = 'a5d2bf5b7ac4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userProfileId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('licenceNumber', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('skills', sa.String(), nullable=True),
    sa.Column('startDate', sa.TIMESTAMP(), nullable=True),
    sa.Column('endDate', sa.TIMESTAMP(), nullable=True),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userProfileId'], ['users_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userProfileId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('skills', sa.String(), nullable=True),
    sa.Column('startDate', sa.TIMESTAMP(), nullable=True),
    sa.Column('endDate', sa.TIMESTAMP(), nullable=True),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userProfileId'], ['users_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    op.drop_table('certificates')
    # ### end Alembic commands ###
