"""company model added

Revision ID: de958bc8a12d
Revises: e067bf77198f
Create Date: 2023-01-18 18:44:52.365893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de958bc8a12d'
down_revision = 'e067bf77198f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recruiterId', sa.Integer(), nullable=True),
    sa.Column('adminId', sa.Integer(), nullable=True),
    sa.Column('companyName', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('totalEmployees', sa.Integer(), nullable=True),
    sa.Column('headquartered', sa.String(), nullable=True),
    sa.Column('companyBio', sa.String(), nullable=True),
    sa.Column('companyEmail', sa.String(), nullable=True),
    sa.Column('profilePicUrl', sa.String(), nullable=True),
    sa.Column('bannerPicUrl', sa.String(), nullable=True),
    sa.Column('companyPics', sa.String(), nullable=True),
    sa.Column('founders', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('companyGst', sa.String(), nullable=True),
    sa.Column('websiteLink', sa.String(), nullable=True),
    sa.Column('phoneVerified', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('isVerified', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('isBlocked', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('lastLogin', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['adminId'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recruiterId'], ['recruiter_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('recruiter_profile', sa.Column('isCompanyAdmin', sa.Boolean(), server_default='FALSE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recruiter_profile', 'isCompanyAdmin')
    op.drop_table('companies')
    # ### end Alembic commands ###
