"""added recruiter model relation

Revision ID: e067bf77198f
Revises: d949ec35f24c
Create Date: 2023-01-14 02:39:53.550743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e067bf77198f'
down_revision = 'd949ec35f24c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
